name: Workflow Hola Mundo
on:
  push:
    branches: [ "main" ]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar por consola
        run: echo "Hola Mundo desde GitHub Actions"
